name: Goat
description: Goat App for arabic talents.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.7.12"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get_it: ^7.6.0
  another_flushbar: ^1.12.30
  logger: ^1.3.0
  equatable: ^2.0.5
  device_info_plus: ^9.0.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: any
  flutter_svg: ^2.0.6
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.1.2
  google_fonts: ^4.0.4
  pretty_dio_logger: ^1.3.1
  faker: ^2.1.0
  flutter_spinkit: ^5.2.0
  package_info: ^2.0.2
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  lottie: ^2.3.2
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.0.15
  flutter_fortune_wheel: ^1.2.0
  syncfusion_flutter_gauges: ^21.2.5
  webview_flutter:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  timeline_tile:
  firebase_app_check: ^0.1.4+1
  android_id: ^0.3.3

dependency_overrides:
  intl: ^0.18.1
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/lottie/