// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_3T6-sK_s0qNgRa20nRM5C_jVP3hqYw',
    appId: '1:580322003238:web:ed22db4477b3f310b519e7',
    messagingSenderId: '580322003238',
    projectId: 'test-a4b97',
    authDomain: 'test-a4b97.firebaseapp.com',
    storageBucket: 'test-a4b97.appspot.com',
    measurementId: 'G-G6FV4RNF3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrO3SeQBrRoQow0kEbEFdT5wICaYh0xc',
    appId: '1:580322003238:android:7183669d1fd3c597b519e7',
    messagingSenderId: '580322003238',
    projectId: 'test-a4b97',
    storageBucket: 'test-a4b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgHhVXW1RlJAYW6xR2YaIRsG9cDPweMg',
    appId: '1:580322003238:ios:710b07d399c963acb519e7',
    messagingSenderId: '580322003238',
    projectId: 'test-a4b97',
    storageBucket: 'test-a4b97.appspot.com',
    iosClientId: '580322003238-ttkmj156nc7upgulfc566u2g8o076jkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttermodulearchitecture',
  );
}
